--	ユニットHP回復量補正
INSERT OR REPLACE INTO Modifiers
		(ModifierId, ModifierType)
	VALUES
		('TOMATO_UNIT_HEAL', 'MODIFIER_PLAYER_UNITS_ATTACH_MODIFIER'),
		('TOMATO_UNIT_HEAL_MODIFIER', 'MODIFIER_PLAYER_UNIT_ADJUST_HEAL_PER_TURN');

INSERT OR REPLACE INTO ModifierArguments
		(ModifierId, Name, Value)
	VALUES
		('TOMATO_UNIT_HEAL', 'ModifierId', 'TOMATO_UNIT_HEAL_MODIFIER'),
		('TOMATO_UNIT_HEAL_MODIFIER', 'Amount', 60),
		('TOMATO_UNIT_HEAL_MODIFIER', 'Type', 'ALL');

INSERT OR REPLACE INTO TraitModifiers
		(TraitType, ModifierId)
	VALUES
		('TRAIT_LEADER_SISTER_KOTONOHA', 'TOMATO_UNIT_HEAL');

--	ユニットHP自動回復補正
INSERT OR REPLACE INTO Types
		(Type, Kind)
	VALUES
		('MODIFIER_PLAYER_UNIT_GRANT_HEAL_AFTER_ACTION_TOMATO', 'KIND_MODIFIER');

INSERT OR REPLACE INTO DynamicModifiers
		(ModifierType, CollectionType, EffectType)
	VALUES
		('MODIFIER_PLAYER_UNIT_GRANT_HEAL_AFTER_ACTION_TOMATO', 'COLLECTION_PLAYER_UNITS', 'EFFECT_GRANT_HEAL_AFTER_ACTION');

INSERT OR REPLACE INTO Modifiers
		(ModifierId, ModifierType)
	VALUES
		('URUHA_RUSHIHA_HEAL_EVERY_MOVE', 'MODIFIER_PLAYER_UNIT_GRANT_HEAL_AFTER_ACTION_TOMATO');

INSERT OR REPLACE INTO TraitModifiers
		(TraitType, ModifierId)
	VALUES
		('TRAIT_LEADER_SISTER_KOTONOHA', 'URUHA_RUSHIHA_HEAL_EVERY_MOVE');