--	指導者特性：帆走・造船技術解禁
INSERT OR REPLACE INTO Modifiers
		(ModifierId, ModifierType)
	VALUES
		('MINATO_AQUA_SAILING', 'MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY'),
		('MINATO_AQUA_SHIPBUILDING', 'MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY');

INSERT OR REPLACE INTO ModifierArguments
		(ModifierId, Name, Value)
	VALUES
		('MINATO_AQUA_SAILING', 'TechType', 'TECH_SAILING'),
		('MINATO_AQUA_SHIPBUILDING', 'TechType', 'TECH_SHIPBUILDING');

INSERT OR REPLACE INTO TraitModifiers
		(TraitType, ModifierId)
	VALUES
		('TRAIT_LEADER_SISTER_KOTONOHA', 'MINATO_AQUA_SAILING'),
		('TRAIT_LEADER_SISTER_KOTONOHA', 'MINATO_AQUA_SHIPBUILDING');

--	指導者特性：外洋航行可能
INSERT OR REPLACE INTO Modifiers
		(ModifierId, ModifierType)
	VALUES
		('MINATO_AQUA_EARLY_OCEAN_NAVIGATION', 'MODIFIER_PLAYER_UNITS_ADJUST_VALID_TERRAIN');

INSERT OR REPLACE INTO ModifierArguments
		(ModifierId, Name, Value)
	VALUES
		('MINATO_AQUA_EARLY_OCEAN_NAVIGATION', 'TerrainType', 'TERRAIN_OCEAN'),
		('MINATO_AQUA_EARLY_OCEAN_NAVIGATION', 'Valid', 1);

INSERT OR REPLACE INTO TraitModifiers
		(TraitType, ModifierId)
	VALUES
		('TRAIT_LEADER_SISTER_KOTONOHA', 'MINATO_AQUA_EARLY_OCEAN_NAVIGATION');
