-- 防壁の生産力UP
INSERT OR REPLACE INTO TraitModifiers
		(TraitType, ModifierId)
	VALUES
		('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_WALLS_PRODUCTION'),
		('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_CASTLE_PRODUCTION'),
		('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_TSIKHE_PRODUCTION'),
		('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_STAR_FORT_PRODUCTION');
