-- 区域の生産力を調整
INSERT OR REPLACE INTO Modifiers
		(ModifierId, ModifierType)
	VALUES
		('TRAIT_DISTRICT_PRODUCTION_HOLY_SITE', 'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION'),
		('TRAIT_DISTRICT_PRODUCTION_CAMPUS', 'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION'),
		('TRAIT_DISTRICT_PRODUCTION_THEATER', 'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION'),
		('TRAIT_DISTRICT_PRODUCTION_COMMERCIAL_HUB', 'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION'),
		('TRAIT_DISTRICT_PRODUCTION_HARBOR', 'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION'),
		('TRAIT_DISTRICT_PRODUCTION_INDUSTRIAL_ZONE', 'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION'),
		('TRAIT_DISTRICT_PRODUCTION_ENCAMPMENT', 'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION'),
		('TRAIT_DISTRICT_PRODUCTION_WATER_ENTERTAINMENT_COMPLEX', 'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION'),
		('TRAIT_DISTRICT_PRODUCTION_AERODROME', 'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION'),
		('TRAIT_DISTRICT_PRODUCTION_NEIGHBORHOOD', 'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION'),
		('TRAIT_DISTRICT_PRODUCTION_SPACEPORT', 'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION'),
		('TRAIT_DISTRICT_PRODUCTION_DAM', 'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION'),
		('TRAIT_DISTRICT_PRODUCTION_CANAL', 'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION');

INSERT OR REPLACE INTO ModifierArguments
		(ModifierId, Name, Value)
	VALUES
        -- 聖地
		('TRAIT_DISTRICT_PRODUCTION_HOLY_SITE', 'DistrictType', 'DISTRICT_HOLY_SITE'),
		('TRAIT_DISTRICT_PRODUCTION_HOLY_SITE', 'Amount', 600),
        -- キャンパス
		('TRAIT_DISTRICT_PRODUCTION_CAMPUS', 'DistrictType', 'DISTRICT_CAMPUS'),
		('TRAIT_DISTRICT_PRODUCTION_CAMPUS', 'Amount', 400),
        -- 劇場広場
		('TRAIT_DISTRICT_PRODUCTION_THEATER', 'DistrictType', 'DISTRICT_THEATER'),
		('TRAIT_DISTRICT_PRODUCTION_THEATER', 'Amount', 400),
        -- 商業ハブ
		('TRAIT_DISTRICT_PRODUCTION_COMMERCIAL_HUB', 'DistrictType', 'DISTRICT_COMMERCIAL_HUB'),
		('TRAIT_DISTRICT_PRODUCTION_COMMERCIAL_HUB', 'Amount', 400),
        -- 港
		('TRAIT_DISTRICT_PRODUCTION_HARBOR', 'DistrictType', 'DISTRICT_HARBOR'),
		('TRAIT_DISTRICT_PRODUCTION_HARBOR', 'Amount', 400),
        -- 工業地帯
		('TRAIT_DISTRICT_PRODUCTION_INDUSTRIAL_ZONE', 'DistrictType', 'DISTRICT_INDUSTRIAL_ZONE'),
		('TRAIT_DISTRICT_PRODUCTION_INDUSTRIAL_ZONE', 'Amount', 400),
        -- 総合娯楽施設
		('TRAIT_DISTRICT_PRODUCTION_ENCAMPMENT', 'DistrictType', 'DISTRICT_ENCAMPMENT'),
		('TRAIT_DISTRICT_PRODUCTION_ENCAMPMENT', 'Amount', 200),
        -- ウォーターパーク
		('TRAIT_DISTRICT_PRODUCTION_WATER_ENTERTAINMENT_COMPLEX', 'DistrictType', 'DISTRICT_WATER_ENTERTAINMENT_COMPLEX'),
		('TRAIT_DISTRICT_PRODUCTION_WATER_ENTERTAINMENT_COMPLEX', 'Amount', 200),
        -- 飛行場
		('TRAIT_DISTRICT_PRODUCTION_AERODROME', 'DistrictType', 'DISTRICT_AERODROME'),
		('TRAIT_DISTRICT_PRODUCTION_AERODROME', 'Amount', 200),
        -- 近郊部
		('TRAIT_DISTRICT_PRODUCTION_NEIGHBORHOOD', 'DistrictType', 'DISTRICT_NEIGHBORHOOD'),
		('TRAIT_DISTRICT_PRODUCTION_NEIGHBORHOOD', 'Amount', 200),
        -- 宇宙船基地
		('TRAIT_DISTRICT_PRODUCTION_SPACEPORT', 'DistrictType', 'DISTRICT_SPACEPORT'),
		('TRAIT_DISTRICT_PRODUCTION_SPACEPORT', 'Amount', 200),
        -- ダム
		('TRAIT_DISTRICT_PRODUCTION_DAM', 'DistrictType', 'DISTRICT_DAM'),
		('TRAIT_DISTRICT_PRODUCTION_DAM', 'Amount', 200),
        -- 運河
		('TRAIT_DISTRICT_PRODUCTION_CANAL', 'DistrictType', 'DISTRICT_CANAL'),
		('TRAIT_DISTRICT_PRODUCTION_CANAL', 'Amount', 200);

INSERT OR REPLACE INTO TraitModifiers
		(TraitType, ModifierId)
	VALUES
		('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_DISTRICT_PRODUCTION_HOLY_SITE'),
		('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_DISTRICT_PRODUCTION_CAMPUS'),
		('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_DISTRICT_PRODUCTION_THEATER'),
		('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_DISTRICT_PRODUCTION_COMMERCIAL_HUB'),
		('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_DISTRICT_PRODUCTION_HARBOR'),
		('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_DISTRICT_PRODUCTION_INDUSTRIAL_ZONE'),
		('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_DISTRICT_PRODUCTION_ENCAMPMENT'),
		('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_DISTRICT_PRODUCTION_WATER_ENTERTAINMENT_COMPLEX'),
		('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_DISTRICT_PRODUCTION_AERODROME'),
		('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_DISTRICT_PRODUCTION_NEIGHBORHOOD'),
		('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_DISTRICT_PRODUCTION_SPACEPORT'),
		('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_DISTRICT_PRODUCTION_DAM'),
		('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_DISTRICT_PRODUCTION_CANAL');

