--	ユニットHP回復量補正
INSERT OR REPLACE INTO Modifiers
		(ModifierId, ModifierType)
	VALUES
		('URUHA_RUSHIA_UNIT_HEAL', 'MODIFIER_PLAYER_UNITS_ATTACH_MODIFIER'),
		('URUHA_RUSHIA_UNIT_HEAL_MODIFIER', 'MODIFIER_PLAYER_UNIT_ADJUST_HEAL_PER_TURN');

INSERT OR REPLACE INTO ModifierArguments
		(ModifierId, Name, Value)
	VALUES
		('URUHA_RUSHIA_UNIT_HEAL', 'ModifierId', 'URUHA_RUSHIA_UNIT_HEAL_MODIFIER'),
		('URUHA_RUSHIA_UNIT_HEAL_MODIFIER', 'Amount', 50),
		('URUHA_RUSHIA_UNIT_HEAL_MODIFIER', 'Type', 'ALL');

INSERT OR REPLACE INTO TraitModifiers
		(TraitType, ModifierId)
	VALUES
		('TRAIT_LEADER_SISTER_KOTONOHA', 'URUHA_RUSHIA_UNIT_HEAL');

--	ユニットHP自動回復補正
INSERT OR REPLACE INTO Types
		(Type, Kind)
	VALUES
		('MODIFIER_PLAYER_UNIT_GRANT_HEAL_AFTER_ACTION_URUHA_RUSHIA', 'KIND_MODIFIER');

INSERT OR REPLACE INTO DynamicModifiers
		(ModifierType, CollectionType, EffectType)
	VALUES
		('MODIFIER_PLAYER_UNIT_GRANT_HEAL_AFTER_ACTION_URUHA_RUSHIA', 'COLLECTION_PLAYER_UNITS', 'EFFECT_GRANT_HEAL_AFTER_ACTION');

INSERT OR REPLACE INTO Modifiers
		(ModifierId, ModifierType)
	VALUES
		('URUHA_RUSHIHA_HEAL_EVERY_MOVE', 'MODIFIER_PLAYER_UNIT_GRANT_HEAL_AFTER_ACTION_URUHA_RUSHIA');

INSERT OR REPLACE INTO TraitModifiers
		(TraitType, ModifierId)
	VALUES
		('TRAIT_LEADER_SISTER_KOTONOHA', 'URUHA_RUSHIHA_HEAL_EVERY_MOVE');