
-- INSERT INTO GameModifiers(ModifierId) VALUES
-- ('MOVEMENT_MOVES_ATTACH'),
-- ('MOVEMENT_SIGHT_ATTACH');

-- 全てのユニットの視界と移動を +2
INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
('TRAIT_LEADER_SISTER_KOTONOHA', 'MOVEMENT_MOVES_ATTACH'),
('TRAIT_LEADER_SISTER_KOTONOHA', 'MOVEMENT_SIGHT_ATTACH');

INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
('MOVEMENT_MOVES_ATTACH', 'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER'),
('MOVEMENT_MOVES', 'MODIFIER_PLAYER_UNITS_ADJUST_MOVEMENT'),
('MOVEMENT_SIGHT_ATTACH', 'MODIFIER_ALL_UNITS_ATTACH_MODIFIER'),
('MOVEMENT_SIGHT', 'MODIFIER_PLAYER_UNIT_ADJUST_SIGHT');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
('MOVEMENT_MOVES_ATTACH', 'ModifierId', 'MOVEMENT_MOVES'),
('MOVEMENT_MOVES', 'Amount', 2),
('MOVEMENT_SIGHT_ATTACH', 'ModifierId', 'MOVEMENT_SIGHT'),
('MOVEMENT_SIGHT', 'Amount', 2);
