-- 信仰力でユニットを購入
INSERT OR REPLACE INTO Modifiers
        (ModifierId, ModifierType)
    VALUES
        -- 陸上軍事ユニット
        ('TRAIT_RECON_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        ('TRAIT_MELEE_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        ('TRAIT_RANGE_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        ('TRAIT_SIEGE_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        ('TRAIT_HEAVY_CAVALRY_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        ('TRAIT_LIGHT_CAVALRY_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        ('TRAIT_RANGED_CAVALRY_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        ('TRAIT_ANTI_CAVALRY_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        ('TRAIT_HEAVY_CHARIOT_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        ('TRAIT_LIGHT_CHARIO_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        -- 海洋軍事ユニット
        ('TRAIT_NAVAL_MELEE_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        ('TRAIT_NAVAL_RANGED_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        ('TRAIT_NAVAL_RAIDER_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        ('TRAIT_NAVAL_CARRIER_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE');

INSERT OR REPLACE INTO ModifierArguments
        (ModifierId, Name, Value)
    VALUES
        -- 陸上軍事ユニット
        ('TRAIT_RECON_FAITH', 'Tag', 'CLASS_RECON'),
        ('TRAIT_MELEE_FAITH', 'Tag', 'CLASS_MELEE'),
        ('TRAIT_RANGE_FAITH', 'Tag', 'CLASS_RANGED'),
        ('TRAIT_SIEGE_FAITH', 'Tag', 'CLASS_SIEGE'),
        ('TRAIT_HEAVY_CAVALRY_FAITH', 'Tag', 'CLASS_HEAVY_CAVALRY'),
        ('TRAIT_LIGHT_CAVALRY_FAITH', 'Tag', 'CLASS_LIGHT_CAVALRY'),
        ('TRAIT_RANGED_CAVALRY_FAITH', 'Tag', 'CLASS_RANGED_CAVALRY'),
        ('TRAIT_ANTI_CAVALRY_FAITH', 'Tag', 'CLASS_ANTI_CAVALRY'),
        ('TRAIT_HEAVY_CHARIOT_FAITH', 'Tag', 'CLASS_HEAVY_CHARIOT'),
        ('TRAIT_LIGHT_CHARIO_FAITH', 'Tag', 'CLASS_LIGHT_CHARIOT'),
        -- 海洋軍事ユニット
        ('TRAIT_NAVAL_MELEE_FAITH', 'Tag', 'CLASS_NAVAL_MELEE'),
        ('TRAIT_NAVAL_RANGED_FAITH', 'Tag', 'CLASS_NAVAL_RANGED'),
        ('TRAIT_NAVAL_RAIDER_FAITH', 'Tag', 'CLASS_NAVAL_RAIDER'),
        ('TRAIT_NAVAL_CARRIER_FAITH', 'Tag', 'CLASS_NAVAL_CARRIER');

INSERT OR REPLACE INTO TraitModifiers
        (TraitType, ModifierId)
    VALUES
        -- 陸上軍事ユニット
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_RECON_FAITH'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_MELEE_FAITH'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_RANGE_FAITH'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_SIEGE_FAITH'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_HEAVY_CAVALRY_FAITH'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_LIGHT_CAVALRY_FAITH'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_RANGED_CAVALRY_FAITH'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_ANTI_CAVALRY_FAITH'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_HEAVY_CHARIOT_FAITH'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_LIGHT_CHARIO_FAITH'),
        -- 海洋軍事ユニット
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_NAVAL_MELEE_FAITH'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_NAVAL_RANGED_FAITH'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_NAVAL_RAIDER_FAITH'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_NAVAL_CARRIER_FAITH');

