-- 信仰力でユニットを購入
INSERT OR REPLACE INTO Modifiers
        (ModifierId, ModifierType)
    VALUES
        --
        ('TRAIT_BUILDER_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        ('TRAIT_TRADER_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        ('TRAIT_SPY_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        -- 陸上軍事ユニット
        ('TRAIT_RECON_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        ('TRAIT_MELEE_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        ('TRAIT_RANGE_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        ('TRAIT_SIEGE_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        ('TRAIT_HEAVY_CAVALRY_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        ('TRAIT_LIGHT_CAVALRY_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        ('TRAIT_RANGED_CAVALRY_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        ('TRAIT_ANTI_CAVALRY_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        ('TRAIT_HEAVY_CHARIOT_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        ('TRAIT_LIGHT_CHARIO_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        ('TRAIT_BATTERING_RAM_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        ('TRAIT_SIEGE_TOWER_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        ('TRAIT_MEDIC_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        -- 航空ユニット
        ('TRAIT_AIRCRAFT_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        ('TRAIT_AIR_BOMBER_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        ('TRAIT_AIR_FIGHTER_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        -- 海洋軍事ユニット
        ('TRAIT_NAVAL_MELEE_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        ('TRAIT_NAVAL_RANGED_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        ('TRAIT_NAVAL_RAIDER_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE'),
        ('TRAIT_NAVAL_CARRIER_FAITH', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE');

INSERT OR REPLACE INTO ModifierArguments
        (ModifierId, Name, Value)
    VALUES
        -- 労働者
        ('TRAIT_BUILDER_FAITH', 'Tag', 'CLASS_BUILDER'),
        -- 交易商
        ('TRAIT_TRADER_FAITH', 'Tag', 'CLASS_TRADER'),
        -- スパイ
        ('TRAIT_SPY_FAITH', 'Tag', 'CLASS_SPY'),
        -- 陸上軍事ユニット
        ('TRAIT_RECON_FAITH', 'Tag', 'CLASS_RECON'),
        ('TRAIT_MELEE_FAITH', 'Tag', 'CLASS_MELEE'),
        ('TRAIT_RANGE_FAITH', 'Tag', 'CLASS_RANGED'),
        ('TRAIT_SIEGE_FAITH', 'Tag', 'CLASS_SIEGE'),
        ('TRAIT_HEAVY_CAVALRY_FAITH', 'Tag', 'CLASS_HEAVY_CAVALRY'),
        ('TRAIT_LIGHT_CAVALRY_FAITH', 'Tag', 'CLASS_LIGHT_CAVALRY'),
        ('TRAIT_RANGED_CAVALRY_FAITH', 'Tag', 'CLASS_RANGED_CAVALRY'),
        ('TRAIT_ANTI_CAVALRY_FAITH', 'Tag', 'CLASS_ANTI_CAVALRY'),
        ('TRAIT_HEAVY_CHARIOT_FAITH', 'Tag', 'CLASS_HEAVY_CHARIOT'),
        ('TRAIT_LIGHT_CHARIO_FAITH', 'Tag', 'CLASS_LIGHT_CHARIOT'),
        -- 破城槌
        ('TRAIT_BATTERING_RAM_FAITH', 'Tag', 'CLASS_BATTERING_RAM'),
        -- 攻城塔
        ('TRAIT_SIEGE_TOWER_FAITH', 'Tag', 'CLASS_SIEGE_TOWER'),
        -- 衛生兵
        ('TRAIT_MEDIC_FAITH', 'Tag', 'CLASS_MEDIC'),
        -- 航空ユニット
        ('TRAIT_AIRCRAFT_FAITH', 'Tag', 'CLASS_AIRCRAFT'),
        ('TRAIT_AIR_BOMBER_FAITH', 'Tag', 'CLASS_AIR_BOMBER'),
        ('TRAIT_AIR_FIGHTER_FAITH', 'Tag', 'CLASS_AIR_FIGHTER'),
        -- 海洋軍事ユニット
        ('TRAIT_NAVAL_MELEE_FAITH', 'Tag', 'CLASS_NAVAL_MELEE'),
        ('TRAIT_NAVAL_RANGED_FAITH', 'Tag', 'CLASS_NAVAL_RANGED'),
        ('TRAIT_NAVAL_RAIDER_FAITH', 'Tag', 'CLASS_NAVAL_RAIDER'),
        ('TRAIT_NAVAL_CARRIER_FAITH', 'Tag', 'CLASS_NAVAL_CARRIER');

INSERT OR REPLACE INTO TraitModifiers
        (TraitType, ModifierId)
    VALUES
        --
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_BUILDER_FAITH'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_TRADER_FAITH'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_SPY_FAITH'),
        -- 陸上軍事ユニット
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_RECON_FAITH'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_MELEE_FAITH'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_RANGE_FAITH'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_SIEGE_FAITH'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_HEAVY_CAVALRY_FAITH'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_LIGHT_CAVALRY_FAITH'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_RANGED_CAVALRY_FAITH'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_ANTI_CAVALRY_FAITH'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_HEAVY_CHARIOT_FAITH'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_LIGHT_CHARIO_FAITH'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_BATTERING_RAM_FAITH'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_SIEGE_TOWER_FAITH'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_MEDIC_FAITH'),
        -- 航空ユニット
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_AIRCRAFT_FAITH'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_AIR_BOMBER_FAITH'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_AIR_FIGHTER_FAITH'),
        -- 海洋軍事ユニット
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_NAVAL_MELEE_FAITH'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_NAVAL_RANGED_FAITH'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_NAVAL_RAIDER_FAITH'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_NAVAL_CARRIER_FAITH');

