-- 資源を最初から見ることがでる
-- 石油、硝酸塩、鉄、石炭、アルミニウム、ウランの資源を最初から見ることがで

INSERT INTO TraitModifiers
        (TraitType, ModifierId)
    VALUES
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'MODIFIER_KANCOLLE_REVEAL_OIL'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'MODIFIER_KANCOLLE_REVEAL_NITER'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'MODIFIER_KANCOLLE_REVEAL_IRON'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'MODIFIER_KANCOLLE_REVEAL_COAL'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'MODIFIER_KANCOLLE_REVEAL_ALUMINUM'),
        ('TRAIT_LEADER_SISTER_KOTONOHA', 'MODIFIER_KANCOLLE_REVEAL_URANIUM');
INSERT INTO Modifiers
        (ModifierId, ModifierType)
    VALUES
        ('MODIFIER_KANCOLLE_REVEAL_OIL', 'MODIFIER_PLAYER_GRANT_FREE_RESOURCE_VISIBILITY'),
        ('MODIFIER_KANCOLLE_REVEAL_NITER', 'MODIFIER_PLAYER_GRANT_FREE_RESOURCE_VISIBILITY'),
        ('MODIFIER_KANCOLLE_REVEAL_IRON', 'MODIFIER_PLAYER_GRANT_FREE_RESOURCE_VISIBILITY'),
        ('MODIFIER_KANCOLLE_REVEAL_COAL', 'MODIFIER_PLAYER_GRANT_FREE_RESOURCE_VISIBILITY'),
        ('MODIFIER_KANCOLLE_REVEAL_ALUMINUM', 'MODIFIER_PLAYER_GRANT_FREE_RESOURCE_VISIBILITY'),
        ('MODIFIER_KANCOLLE_REVEAL_URANIUM', 'MODIFIER_PLAYER_GRANT_FREE_RESOURCE_VISIBILITY');
INSERT INTO ModifierArguments
        (ModifierId, Name, Value)
    VALUES
        -- 石油
        ('MODIFIER_KANCOLLE_REVEAL_OIL', 'ResourceType', 'RESOURCE_OIL'),
        -- 硝石
        ('MODIFIER_KANCOLLE_REVEAL_NITER', 'ResourceType', 'RESOURCE_NITER'),
        -- 鉄
        ('MODIFIER_KANCOLLE_REVEAL_IRON', 'ResourceType', 'RESOURCE_IRON'),
        -- 石炭
        ('MODIFIER_KANCOLLE_REVEAL_COAL', 'ResourceType', 'RESOURCE_COAL'),
        -- アルミニウム
        ('MODIFIER_KANCOLLE_REVEAL_ALUMINUM', 'ResourceType', 'RESOURCE_ALUMINUM'),
        -- ウラン
        ('MODIFIER_KANCOLLE_REVEAL_URANIUM', 'ResourceType', 'RESOURCE_URANIUM');
