--	指導者特性：技術解禁
INSERT OR REPLACE INTO Modifiers
		(ModifierId, ModifierType)
	VALUES
		-- -- 畜産
		-- ('TOMATO_TECH_ANIMAL_HUSBANDRY', 'MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY'),
		-- 帆走術
		('MINATO_AQUA_SAILING', 'MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY'),
		-- 造船
		('MINATO_AQUA_SHIPBUILDING', 'MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY'),
		-- 占星術
		('TOMATO_TECH_ASTROLOGY', 'MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY');

INSERT OR REPLACE INTO ModifierArguments
		(ModifierId, Name, Value)
	VALUES
		-- -- 畜産
		-- ('TOMATO_TECH_ANIMAL_HUSBANDRY', 'TechType', 'TECH_ANIMAL_HUSBANDRY'),
		-- 帆走術
		('MINATO_AQUA_SAILING', 'TechType', 'TECH_SAILING'),
		-- 造船
		('MINATO_AQUA_SHIPBUILDING', 'TechType', 'TECH_SHIPBUILDING'),
		-- 占星術
		('TOMATO_TECH_ASTROLOGY', 'TechType', 'TECH_ASTROLOGY');

INSERT OR REPLACE INTO TraitModifiers
		(TraitType, ModifierId)
	VALUES
		-- -- 畜産
		-- ('TRAIT_LEADER_SISTER_KOTONOHA', 'TOMATO_TECH_ANIMAL_HUSBANDRY'),
		-- 帆走術
		('TRAIT_LEADER_SISTER_KOTONOHA', 'MINATO_AQUA_SAILING'),
		-- 造船
		('TRAIT_LEADER_SISTER_KOTONOHA', 'MINATO_AQUA_SHIPBUILDING'),
		-- 占星術
		('TRAIT_LEADER_SISTER_KOTONOHA', 'TOMATO_TECH_ASTROLOGY');


--	指導者特性：外洋航行可能
INSERT OR REPLACE INTO Modifiers
		(ModifierId, ModifierType)
	VALUES
		('MINATO_AQUA_EARLY_OCEAN_NAVIGATION', 'MODIFIER_PLAYER_UNITS_ADJUST_VALID_TERRAIN');

INSERT OR REPLACE INTO ModifierArguments
		(ModifierId, Name, Value)
	VALUES
		('MINATO_AQUA_EARLY_OCEAN_NAVIGATION', 'TerrainType', 'TERRAIN_OCEAN'),
		('MINATO_AQUA_EARLY_OCEAN_NAVIGATION', 'Valid', 1);

INSERT OR REPLACE INTO TraitModifiers
		(TraitType, ModifierId)
	VALUES
		('TRAIT_LEADER_SISTER_KOTONOHA', 'MINATO_AQUA_EARLY_OCEAN_NAVIGATION');
