

--	指導者固有能力：全ユニット移動力+3
INSERT OR REPLACE INTO Modifiers
		(ModifierId, ModifierType)
	VALUES
		('TOMATO_ADJUST_UNITS_MOVEMENT', 'MODIFIER_PLAYER_UNITS_ADJUST_MOVEMENT');
INSERT OR REPLACE INTO ModifierArguments
		(ModifierId, Name, Value)
	VALUES
		('TOMATO_ADJUST_UNITS_MOVEMENT', 'Amount', 3);
INSERT OR REPLACE INTO TraitModifiers
		(TraitType, ModifierId)
	VALUES
		('TRAIT_LEADER_SISTER_KOTONOHA', 'TOMATO_ADJUST_UNITS_MOVEMENT');

--	指導者固有能力：全ユニット視界+3
INSERT OR REPLACE INTO Modifiers
		(ModifierId, ModifierType)
	VALUES
		('TOMATO_ADJUST_UNITS_SIGHT', 'MODIFIER_PLAYER_UNITS_ADJUST_SIGHT');
INSERT OR REPLACE INTO ModifierArguments
		(ModifierId, Name, Value)
	VALUES
		('TOMATO_ADJUST_UNITS_SIGHT', 'Amount', 3);
INSERT OR REPLACE INTO TraitModifiers
		(TraitType, ModifierId)
	VALUES
		('TRAIT_LEADER_SISTER_KOTONOHA', 'TOMATO_ADJUST_UNITS_SIGHT');


-- INSERT INTO GameModifiers(ModifierId) VALUES
-- ('MOVEMENT_MOVES_ATTACH'),
-- ('MOVEMENT_SIGHT_ATTACH');

-- -- 全てのユニットの視界と移動を +2
-- INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
-- ('TRAIT_LEADER_SISTER_KOTONOHA', 'MOVEMENT_MOVES_ATTACH'),
-- ('TRAIT_LEADER_SISTER_KOTONOHA', 'MOVEMENT_SIGHT_ATTACH');

-- INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
-- ('MOVEMENT_MOVES_ATTACH', 'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER'),
-- ('MOVEMENT_MOVES', 'MODIFIER_PLAYER_UNITS_ADJUST_MOVEMENT'),
-- ('MOVEMENT_SIGHT_ATTACH', 'MODIFIER_ALL_UNITS_ATTACH_MODIFIER'),
-- ('MOVEMENT_SIGHT', 'MODIFIER_PLAYER_UNIT_ADJUST_SIGHT');

-- INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
-- ('MOVEMENT_MOVES_ATTACH', 'ModifierId', 'MOVEMENT_MOVES'),
-- ('MOVEMENT_MOVES', 'Amount', 2),
-- ('MOVEMENT_SIGHT_ATTACH', 'ModifierId', 'MOVEMENT_SIGHT'),
-- ('MOVEMENT_SIGHT', 'Amount', 2);

