-- 信仰力で建築物を購入

-- 商業ハブ
INSERT OR REPLACE INTO Modifiers
		(ModifierId, ModifierType)
	VALUES
		('TRAIT_CITIES_ENABLE_BUILDING_FAITH_PURCHASE_COMMERCIAL_HUB', 'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE');
INSERT OR REPLACE INTO ModifierArguments
		(ModifierId, Name, Value)
	VALUES
		('TRAIT_CITIES_ENABLE_BUILDING_FAITH_PURCHASE_COMMERCIAL_HUB', 'DistrictType', 'DISTRICT_COMMERCIAL_HUB');
INSERT OR REPLACE INTO TraitModifiers
		(TraitType, ModifierId)
	VALUES
		('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_CITIES_ENABLE_BUILDING_FAITH_PURCHASE_COMMERCIAL_HUB');

-- キャンバス
INSERT OR REPLACE INTO Modifiers
		(ModifierId, ModifierType)
	VALUES
		('TRAIT_CITIES_ENABLE_BUILDING_FAITH_PURCHASE_CAMPUS', 'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE');
INSERT OR REPLACE INTO ModifierArguments
		(ModifierId, Name, Value)
	VALUES
		('TRAIT_CITIES_ENABLE_BUILDING_FAITH_PURCHASE_CAMPUS', 'DistrictType', 'DISTRICT_CAMPUS');
INSERT OR REPLACE INTO TraitModifiers
		(TraitType, ModifierId)
	VALUES
		('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_CITIES_ENABLE_BUILDING_FAITH_PURCHASE_CAMPUS');

-- 兵舎
INSERT OR REPLACE INTO Modifiers
		(ModifierId, ModifierType)
	VALUES
		('TRAIT_CITIES_ENABLE_BUILDING_FAITH_PURCHASE_ENCAMPMENT', 'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE');
INSERT OR REPLACE INTO ModifierArguments
		(ModifierId, Name, Value)
	VALUES
		('TRAIT_CITIES_ENABLE_BUILDING_FAITH_PURCHASE_ENCAMPMENT', 'DistrictType', 'DISTRICT_ENCAMPMENT');
INSERT OR REPLACE INTO TraitModifiers
		(TraitType, ModifierId)
	VALUES
		('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_CITIES_ENABLE_BUILDING_FAITH_PURCHASE_ENCAMPMENT');

-- 港
INSERT OR REPLACE INTO Modifiers
		(ModifierId, ModifierType)
	VALUES
		('TRAIT_CITIES_ENABLE_BUILDING_FAITH_PURCHASE_HARBOR', 'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE');
INSERT OR REPLACE INTO ModifierArguments
		(ModifierId, Name, Value)
	VALUES
		('TRAIT_CITIES_ENABLE_BUILDING_FAITH_PURCHASE_HARBOR', 'DistrictType', 'DISTRICT_HARBOR');
INSERT OR REPLACE INTO TraitModifiers
		(TraitType, ModifierId)
	VALUES
		('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_CITIES_ENABLE_BUILDING_FAITH_PURCHASE_HARBOR');

-- 飛行場
INSERT OR REPLACE INTO Modifiers
		(ModifierId, ModifierType)
	VALUES
		('TRAIT_CITIES_ENABLE_BUILDING_FAITH_PURCHASE_AERODROME', 'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE');
INSERT OR REPLACE INTO ModifierArguments
		(ModifierId, Name, Value)
	VALUES
		('TRAIT_CITIES_ENABLE_BUILDING_FAITH_PURCHASE_AERODROME', 'DistrictType', 'DISTRICT_AERODROME');
INSERT OR REPLACE INTO TraitModifiers
		(TraitType, ModifierId)
	VALUES
		('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_CITIES_ENABLE_BUILDING_FAITH_PURCHASE_AERODROME');

-- 工業地帯
INSERT OR REPLACE INTO Modifiers
		(ModifierId, ModifierType)
	VALUES
		('TRAIT_CITIES_ENABLE_BUILDING_FAITH_PURCHASE_INDUSTRIAL_ZONE', 'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE');
INSERT OR REPLACE INTO ModifierArguments
		(ModifierId, Name, Value)
	VALUES
		('TRAIT_CITIES_ENABLE_BUILDING_FAITH_PURCHASE_INDUSTRIAL_ZONE', 'DistrictType', 'DISTRICT_INDUSTRIAL_ZONE');
INSERT OR REPLACE INTO TraitModifiers
		(TraitType, ModifierId)
	VALUES
		('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_CITIES_ENABLE_BUILDING_FAITH_PURCHASE_INDUSTRIAL_ZONE');

-- 近郊街
INSERT OR REPLACE INTO Modifiers
		(ModifierId, ModifierType)
	VALUES
		('TRAIT_CITIES_ENABLE_BUILDING_FAITH_PURCHASE_NEIGHBORHOOD', 'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE');
INSERT OR REPLACE INTO ModifierArguments
		(ModifierId, Name, Value)
	VALUES
		('TRAIT_CITIES_ENABLE_BUILDING_FAITH_PURCHASE_NEIGHBORHOOD', 'DistrictType', 'DISTRICT_NEIGHBORHOOD');
INSERT OR REPLACE INTO TraitModifiers
		(TraitType, ModifierId)
	VALUES
		('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_CITIES_ENABLE_BUILDING_FAITH_PURCHASE_NEIGHBORHOOD');

-- 用水路
INSERT OR REPLACE INTO Modifiers
		(ModifierId, ModifierType)
	VALUES
		('TRAIT_CITIES_ENABLE_BUILDING_FAITH_PURCHASE_AQUEDUCT', 'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE');
INSERT OR REPLACE INTO ModifierArguments
		(ModifierId, Name, Value)
	VALUES
		('TRAIT_CITIES_ENABLE_BUILDING_FAITH_PURCHASE_AQUEDUCT', 'DistrictType', 'DISTRICT_AQUEDUCT');
INSERT OR REPLACE INTO TraitModifiers
		(TraitType, ModifierId)
	VALUES
		('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_CITIES_ENABLE_BUILDING_FAITH_PURCHASE_AQUEDUCT');

-- 商業ハブ
INSERT OR REPLACE INTO Modifiers
		(ModifierId, ModifierType)
	VALUES
		('TRAIT_CITIES_ENABLE_BUILDING_FAITH_PURCHASE_AQUEDUCT', 'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE');
INSERT OR REPLACE INTO ModifierArguments
		(ModifierId, Name, Value)
	VALUES
		('TRAIT_CITIES_ENABLE_BUILDING_FAITH_PURCHASE_AQUEDUCT', 'DistrictType', 'DISTRICT_AQUEDUCT');
INSERT OR REPLACE INTO TraitModifiers
		(TraitType, ModifierId)
	VALUES
		('TRAIT_LEADER_SISTER_KOTONOHA', 'TRAIT_CITIES_ENABLE_BUILDING_FAITH_PURCHASE_AQUEDUCT');

