-- --	必要条件：キャンパス区域
-- INSERT OR REPLACE INTO RequirementSets
-- 		(RequirementSetId, RequirementSetType)
-- 	VALUES
-- 		('REQUIREMENT_SET_MURASAKI_SHION_CAMPUS', 'REQUIREMENTSET_TEST_ALL');

-- INSERT OR REPLACE INTO RequirementSetRequirements
-- 		(RequirementSetId, RequirementId)
-- 	VALUES
-- 		('REQUIREMENT_SET_MURASAKI_SHION_CAMPUS', 'REQUIRES_CITY_HAS_CAMPUS');

-- --	必要条件：図書館
-- INSERT OR REPLACE INTO Requirements
-- 		(RequirementId, RequirementType)
-- 	VALUES
-- 		('REQUIRES_MURASAKI_SHION_CITY_HAS_LIBRARY', 'REQUIREMENT_CITY_HAS_BUILDING');

-- INSERT OR REPLACE INTO RequirementArguments
-- 		(RequirementId, Name, Value)
-- 	VALUES
-- 		('REQUIRES_MURASAKI_SHION_CITY_HAS_LIBRARY', 'BuildingType', 'BUILDING_LIBRARY');

-- INSERT OR REPLACE INTO RequirementSets
-- 		(RequirementSetId, RequirementSetType)
-- 	VALUES
-- 		('REQUIREMENT_SET_MURASAKI_SHION_LIBRARY', 'REQUIREMENTSET_TEST_ALL');

-- INSERT OR REPLACE INTO RequirementSetRequirements
-- 		(RequirementSetId, RequirementId)
-- 	VALUES
-- 		('REQUIREMENT_SET_MURASAKI_SHION_LIBRARY', 'REQUIRES_MURASAKI_SHION_CITY_HAS_LIBRARY');

-- --	必要条件：大学
-- INSERT OR REPLACE INTO Requirements
-- 		(RequirementId, RequirementType)
-- 	VALUES
-- 		('REQUIRES_MURASAKI_SHION_CITY_HAS_UNIVERSITY', 'REQUIREMENT_CITY_HAS_BUILDING');

-- INSERT OR REPLACE INTO RequirementArguments
-- 		(RequirementId, Name, Value)
-- 	VALUES
-- 		('REQUIRES_MURASAKI_SHION_CITY_HAS_UNIVERSITY', 'BuildingType', 'BUILDING_UNIVERSITY');

-- INSERT OR REPLACE INTO RequirementSets
-- 		(RequirementSetId, RequirementSetType)
-- 	VALUES
-- 		('REQUIREMENT_SET_MURASAKI_SHION_UNIVERSITY', 'REQUIREMENTSET_TEST_ALL');

-- INSERT OR REPLACE INTO RequirementSetRequirements
-- 		(RequirementSetId, RequirementId)
-- 	VALUES
-- 		('REQUIREMENT_SET_MURASAKI_SHION_UNIVERSITY', 'REQUIRES_MURASAKI_SHION_CITY_HAS_UNIVERSITY');

-- --	必要条件：研究所
-- INSERT OR REPLACE INTO Requirements
-- 		(RequirementId, RequirementType)
-- 	VALUES
-- 		('REQUIRES_MURASAKI_SHION_CITY_HAS_RESEARCH_LAB', 'REQUIREMENT_CITY_HAS_BUILDING');

-- INSERT OR REPLACE INTO RequirementArguments
-- 		(RequirementId, Name, Value)
-- 	VALUES
-- 		('REQUIRES_MURASAKI_SHION_CITY_HAS_RESEARCH_LAB', 'BuildingType', 'BUILDING_RESEARCH_LAB');

-- INSERT OR REPLACE INTO RequirementSets
-- 		(RequirementSetId, RequirementSetType)
-- 	VALUES
-- 		('REQUIREMENT_SET_MURASAKI_SHION_RESEARCH_LAB', 'REQUIREMENTSET_TEST_ALL');

-- INSERT OR REPLACE INTO RequirementSetRequirements
-- 		(RequirementSetId, RequirementId)
-- 	VALUES
-- 		('REQUIREMENT_SET_MURASAKI_SHION_RESEARCH_LAB', 'REQUIRES_MURASAKI_SHION_CITY_HAS_RESEARCH_LAB');

-- --	文明特性：都市出力増幅
-- INSERT OR REPLACE INTO Modifiers
-- 		(ModifierId, ModifierType, SubjectRequirementSetId)
-- 	VALUES
-- 		('MURASAKI_SHION_SCIENCE_CAMPUS', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'REQUIREMENT_SET_MURASAKI_SHION_CAMPUS'),
-- 		('MURASAKI_SHION_SCIENCE_LIBRARY', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'REQUIREMENT_SET_MURASAKI_SHION_LIBRARY'),
-- 		('MURASAKI_SHION_SCIENCE_UNIVERSITY', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'REQUIREMENT_SET_MURASAKI_SHION_UNIVERSITY'),
-- 		('MURASAKI_SHION_SCIENCE_RESEARCH_LAB', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'REQUIREMENT_SET_MURASAKI_SHION_RESEARCH_LAB');

-- INSERT OR REPLACE INTO ModifierArguments
-- 		(ModifierId, Name, Value)
-- 	VALUES
-- 		('MURASAKI_SHION_SCIENCE_CAMPUS', 'YieldType', 'YIELD_SCIENCE'),
-- 		('MURASAKI_SHION_SCIENCE_CAMPUS', 'Amount', 20),
-- 		('MURASAKI_SHION_SCIENCE_LIBRARY', 'YieldType', 'YIELD_SCIENCE'),
-- 		('MURASAKI_SHION_SCIENCE_LIBRARY', 'Amount', 20),
-- 		('MURASAKI_SHION_SCIENCE_UNIVERSITY', 'YieldType', 'YIELD_SCIENCE'),
-- 		('MURASAKI_SHION_SCIENCE_UNIVERSITY', 'Amount', 20),
-- 		('MURASAKI_SHION_SCIENCE_RESEARCH_LAB', 'YieldType', 'YIELD_SCIENCE'),
-- 		('MURASAKI_SHION_SCIENCE_RESEARCH_LAB', 'Amount', 20);

-- INSERT OR REPLACE INTO TraitModifiers
-- 		(TraitType, ModifierId)
-- 	VALUES
-- 		('TRAIT_CIVILIZATION_MURASAKI_SHION', 'MURASAKI_SHION_SCIENCE_CAMPUS'),
-- 		('TRAIT_CIVILIZATION_MURASAKI_SHION', 'MURASAKI_SHION_SCIENCE_LIBRARY'),
-- 		('TRAIT_CIVILIZATION_MURASAKI_SHION', 'MURASAKI_SHION_SCIENCE_UNIVERSITY'),
-- 		('TRAIT_CIVILIZATION_MURASAKI_SHION', 'MURASAKI_SHION_SCIENCE_RESEARCH_LAB');

--	補正：射程増加
INSERT OR REPLACE INTO Modifiers
		(ModifierId, ModifierType)
	VALUES
		('MURASAKI_SHION_ATTACK_RANGE', 'MODIFIER_UNIT_ADJUST_ATTACK_RANGE');

INSERT OR REPLACE INTO ModifierArguments
		(ModifierId, Name, Value)
	VALUES
		('MURASAKI_SHION_ATTACK_RANGE', 'Amount', 3);

--	ユニット能力：射程増加補正
INSERT OR REPLACE INTO Types
		(Type, Kind)
	VALUES
		('ABILITY_MURASAKI_SHION_ATTACK_RANGE', 'KIND_ABILITY');

INSERT OR REPLACE INTO TypeTags
		(Type, Tag)
	VALUES
		('ABILITY_MURASAKI_SHION_ATTACK_RANGE', 'CLASS_RANGED'),
		('ABILITY_MURASAKI_SHION_ATTACK_RANGE', 'CLASS_RANGED_CAVALRY'),
		('ABILITY_MURASAKI_SHION_ATTACK_RANGE', 'CLASS_SIEGE'),
		('ABILITY_MURASAKI_SHION_ATTACK_RANGE', 'CLASS_NAVAL_RANGED'),
		('ABILITY_MURASAKI_SHION_ATTACK_RANGE', 'CLASS_NAVAL_RAIDER');

INSERT OR REPLACE INTO UnitAbilities
		(UnitAbilityType, Name, Description, Inactive)
	VALUES
		('ABILITY_MURASAKI_SHION_ATTACK_RANGE', 'LOC_ABILITY_MURASAKI_SHION_ATTACK_RANGE_NAME', 'LOC_ABILITY_MURASAKI_SHION_ATTACK_RANGE_DESCRIPTION', 1);

INSERT OR REPLACE INTO UnitAbilityModifiers
		(UnitAbilityType, ModifierId)
	VALUES
		('ABILITY_MURASAKI_SHION_ATTACK_RANGE', 'MURASAKI_SHION_ATTACK_RANGE');

--	文明特性：ユニット能力付与
INSERT OR REPLACE INTO Modifiers
		(ModifierId, ModifierType, Permanent)
	VALUES
		('MURASAKI_SHION_GRANT_RANGE_ABILITY', 'MODIFIER_PLAYER_UNITS_GRANT_ABILITY', 1);

INSERT OR REPLACE INTO ModifierArguments
		(ModifierId, Name, Value)
	VALUES
		('MURASAKI_SHION_GRANT_RANGE_ABILITY', 'AbilityType', 'ABILITY_MURASAKI_SHION_ATTACK_RANGE');

INSERT OR REPLACE INTO TraitModifiers
		(TraitType, ModifierId)
	VALUES
		('TRAIT_LEADER_SISTER_KOTONOHA', 'MURASAKI_SHION_GRANT_RANGE_ABILITY');
