--	補正：射程増加
INSERT OR REPLACE INTO Modifiers
		(ModifierId, ModifierType)
	VALUES
		('MURASAKI_SHION_ATTACK_RANGE', 'MODIFIER_UNIT_ADJUST_ATTACK_RANGE');

INSERT OR REPLACE INTO ModifierArguments
		(ModifierId, Name, Value)
	VALUES
		('MURASAKI_SHION_ATTACK_RANGE', 'Amount', 6);

--	ユニット能力：射程増加補正
INSERT OR REPLACE INTO Types
		(Type, Kind)
	VALUES
		('ABILITY_MURASAKI_SHION_ATTACK_RANGE', 'KIND_ABILITY');

INSERT OR REPLACE INTO TypeTags
		(Type, Tag)
	VALUES
		('ABILITY_MURASAKI_SHION_ATTACK_RANGE', 'CLASS_RANGED'),
		('ABILITY_MURASAKI_SHION_ATTACK_RANGE', 'CLASS_RANGED_CAVALRY'),
		('ABILITY_MURASAKI_SHION_ATTACK_RANGE', 'CLASS_SIEGE'),
		('ABILITY_MURASAKI_SHION_ATTACK_RANGE', 'CLASS_NAVAL_RANGED'),
		('ABILITY_MURASAKI_SHION_ATTACK_RANGE', 'CLASS_NAVAL_RAIDER');

INSERT OR REPLACE INTO UnitAbilities
		(UnitAbilityType, Name, Description, Inactive)
	VALUES
		('ABILITY_MURASAKI_SHION_ATTACK_RANGE', 'LOC_ABILITY_MURASAKI_SHION_ATTACK_RANGE_NAME', 'LOC_ABILITY_MURASAKI_SHION_ATTACK_RANGE_DESCRIPTION', 1);

INSERT OR REPLACE INTO UnitAbilityModifiers
		(UnitAbilityType, ModifierId)
	VALUES
		('ABILITY_MURASAKI_SHION_ATTACK_RANGE', 'MURASAKI_SHION_ATTACK_RANGE');

--	文明特性：ユニット能力付与
INSERT OR REPLACE INTO Modifiers
		(ModifierId, ModifierType, Permanent)
	VALUES
		('MURASAKI_SHION_GRANT_RANGE_ABILITY', 'MODIFIER_PLAYER_UNITS_GRANT_ABILITY', 1);

INSERT OR REPLACE INTO ModifierArguments
		(ModifierId, Name, Value)
	VALUES
		('MURASAKI_SHION_GRANT_RANGE_ABILITY', 'AbilityType', 'ABILITY_MURASAKI_SHION_ATTACK_RANGE');

INSERT OR REPLACE INTO TraitModifiers
		(TraitType, ModifierId)
	VALUES
		('TRAIT_LEADER_SISTER_KOTONOHA', 'MURASAKI_SHION_GRANT_RANGE_ABILITY');
