-- IconTextureAtlases
INSERT INTO IconTextureAtlases
(Name,											IconSize,	IconsPerRow,	IconsPerColumn, Filename)
VALUES
('ICON_ATLAS_UNITS_FLAC_ACADEMY',				22,			2,				1,				'ICON_UNITS_FLAC_ACADEMY_22'),
('ICON_ATLAS_UNITS_FLAC_ACADEMY',				32,			2,				1,				'ICON_UNITS_FLAC_ACADEMY_32'),
('ICON_ATLAS_UNITS_FLAC_ACADEMY',				38,			2,				1,				'ICON_UNITS_FLAC_ACADEMY_38'),
('ICON_ATLAS_UNITS_FLAC_ACADEMY',				50,			2,				1,				'ICON_UNITS_FLAC_ACADEMY_50'),
('ICON_ATLAS_UNITS_FLAC_ACADEMY',				80,			2,				1,				'ICON_UNITS_FLAC_ACADEMY_80'),
('ICON_ATLAS_UNITS_FLAC_ACADEMY',				256,		2,				1,				'ICON_UNITS_FLAC_ACADEMY_256');

-- IconDefinitions
INSERT INTO IconDefinitions
(Name,										Atlas,										'Index')
VALUES
('ICON_UNIT_FLAC_JUDGEMENT',				'ICON_ATLAS_UNITS_FLAC_ACADEMY',			0),
('ICON_UNIT_FLAC_JUDGEMENT_WHITE',			'ICON_ATLAS_UNITS_FLAC_ACADEMY',			0),
('ICON_UNIT_FLAC_JUDGEMENT_BLACK',			'ICON_ATLAS_UNITS_FLAC_ACADEMY',			0),
('ICON_UNIT_FLAC_JUDGEMENT_PORTRAIT',		'PORTRAITS_ATLAS_UNITS_FLAC_ACADEMY',		0),
-- とりあえず、日本
('ICON_CIVILIZATION_FELINE',				'ICON_ATLAS_CIVILIZATIONS',					12),
-- とりあえず、北条時宗
('ICON_LEADER_JASPER_KITTY',				'ICON_ATLAS_LEADERS',						8);
